---
# handlers file for role_postfix_nullclient

- name: Handler postfix reload
  ansible.builtin.service:
    name: postfix
    state: reloaded
- name: Handler newaliases
  ansible.builtin.command: newaliases
  changed_when: false

...
